CREATE TABLE `capture_sessions` (
	`id` text PRIMARY KEY NOT NULL,
	`operation_id` text NOT NULL,
	`field_id` text NOT NULL,
	`claim_id` text,
	`protocol_version` text DEFAULT 'capture-protocol@1.0' NOT NULL,
	`damage_type` text,
	`days_since_event` integer,
	`growth_stage` text,
	`gsd_cm` real,
	`altitude_m` real,
	`bands` text,
	`ground_control` text,
	`conditions` text,
	`zone_estimates` text,
	`drone_capture_id` text,
	`ground_photo_ids` text DEFAULT '[]' NOT NULL,
	`calibration_grade` integer DEFAULT false NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`operation_id`) REFERENCES `operations`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`field_id`) REFERENCES `fields`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`claim_id`) REFERENCES `claims`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`drone_capture_id`) REFERENCES `imagery_captures`(`id`) ON UPDATE no action ON DELETE no action
);
