/**
 * DEMO ANALYZER — deterministic stand-in for the real CV models.
 *
 * It produces plausible, clearly-demo output derived from a hash of the
 * inputs, so the full pipeline (capture → FCR → evidence packet, with real
 * provenance mechanics) can be exercised end to end before the NDVI/ExG
 * analyzers land (ROADMAP.md Phase 1). Every FCR it emits carries
 * modelName "demo-analyzer", which the UI surfaces as a demo badge —
 * nothing this analyzer produces may be presented as real analysis.
 */
import { createHash } from "crypto";
import type { Analyzer, AnalyzerInput, AnalyzerOutput } from "./types";

const STAGES_BY_MONTH: Record<number, string> = {
  4: "VE–V2", 5: "V3–V6", 6: "V6–V12", 7: "VT/R1", 8: "R2–R4", 9: "R5", 10: "R6",
};

function seededFraction(seed: string, salt: string): number {
  const h = createHash("sha256").update(seed + salt).digest();
  return h.readUInt32BE(0) / 0xffffffff;
}

export const demoAnalyzer: Analyzer = {
  name: "demo-analyzer",
  version: "0.1.0",

  async analyze(input: AnalyzerInput): Promise<AnalyzerOutput> {
    const seed = input.captures.map((c) => c.sha256).sort().join("|") + input.damageType;

    // Severity band by damage type, jittered deterministically by imagery hash
    const base: Record<string, [number, number]> = {
      hail: [35, 80], flood: [45, 95], drought: [20, 55], wind: [25, 65],
      disease: [15, 45], pest: [10, 40], other: [15, 60],
    };
    const [lo, hi] = base[input.damageType] ?? base.other;
    const severityPct = Math.round(lo + seededFraction(seed, "sev") * (hi - lo));
    const affectedFrac = 0.3 + seededFraction(seed, "area") * 0.65;
    const affectedAcres = Math.round(input.fieldAcres * affectedFrac * 10) / 10;

    const month = new Date(input.eventDate).getUTCMonth() + 1;
    const growthStage = STAGES_BY_MONTH[month] ?? null;

    // Healthy-corn NDVI midseason ≈ 0.7–0.85; damage pulls the mean down
    const ndviHealthy = 0.72 + seededFraction(seed, "base") * 0.1;
    const ndviMean = Math.round((ndviHealthy * (1 - severityPct / 130)) * 100) / 100;

    const conditionClass =
      severityPct >= 85 ? "destroyed" : severityPct >= 30 ? "damaged" : "stressed";

    return {
      conditionClass,
      growthStage,
      severityPct,
      affectedAcres,
      metrics: {
        ndvi_mean: ndviMean,
        ndvi_baseline: Math.round(ndviHealthy * 100) / 100,
        canopy_cover_pct: Math.round(100 - severityPct * 0.7),
        affected_area_frac: Math.round(affectedFrac * 100) / 100,
      },
      confidence: Math.round((0.7 + seededFraction(seed, "conf") * 0.2) * 100) / 100,
      narrative:
        `[SAMPLE ANALYSIS] Imagery indicates ${input.damageType} damage across approximately ` +
        `${affectedAcres} of ${input.fieldAcres} acres (${Math.round(affectedFrac * 100)}% of the field), ` +
        `estimated severity ${severityPct}%. Mean vegetation index ${ndviMean} against a ` +
        `pre-event baseline of ${Math.round(ndviHealthy * 100) / 100}. ` +
        `Generated by the demo analyzer — not a real crop assessment.`,
    };
  },
};
